[package]
name = "audio-forge-lonesome-picker"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[lib]
crate-type = ["cdylib"]

[dependencies]
nih_plug = { workspace = true }
nih_plug_vizia = { workspace = true }
atomic_float = { workspace = true }
